# Mathematical Operations

## Load SQL Extension

In [14]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


## Connect to PSQL Database

In [20]:
%sql postgresql://localhost/math_db

In [23]:
%%sql
CREATE TABLE students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    score INTEGER
);

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
Done.


[]

In [24]:
%%sql
INSERT INTO students VALUES
(1,'Alice',85),
(2,'Bob',92),
(3,'Charlie',67),
(4,'David',74),
(5,'Eva',90);

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
5 rows affected.


[]

## List all tables

In [25]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
1 rows affected.


table_name
students


## Basic Arithmetic

In [26]:
%%sql
SELECT name, score, score + 5 AS boosted_score
FROM students;

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
5 rows affected.


name,score,boosted_score
Alice,85,90
Bob,92,97
Charlie,67,72
David,74,79
Eva,90,95


## Multiple Operations

In [27]:
%%sql
SELECT name, score,
       score * 1.1 AS scaled,
       score / 10 AS normalized
FROM students;

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
5 rows affected.


name,score,scaled,normalized
Alice,85,93.5,8
Bob,92,101.2,9
Charlie,67,73.7,6
David,74,81.4,7
Eva,90,99.0,9


## Aggregate Functions

In [28]:
%%sql
SELECT 
AVG(score) AS avg_score,
MAX(score) AS max_score,
MIN(score) AS min_score,
SUM(score) AS total_score,
COUNT(*) AS total_students
FROM students;

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
1 rows affected.


avg_score,max_score,min_score,total_score,total_students
81.6000000000000000,92,67,408,5


## Filtering with Math

In [29]:
%%sql
SELECT *
FROM students
WHERE score > (SELECT AVG(score) FROM students);

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
3 rows affected.


id,name,score
1,Alice,85
2,Bob,92
5,Eva,90


## Mathematical Functions

In [30]:
%%sql
SELECT name, score,
ROUND(score,1),
SQRT(score),
POWER(score,2)
FROM students;

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
5 rows affected.


name,score,round,sqrt,power
Alice,85,85.0,9.219544457292887,7225.0
Bob,92,92.0,9.591663046625438,8464.0
Charlie,67,67.0,8.18535277187245,4489.0
David,74,74.0,8.602325267042627,5476.0
Eva,90,90.0,9.486832980505138,8100.0


# Convert to Pandas

In [31]:
import pandas as pd
result = %sql SELECT * FROM students;
df = result.DataFrame()
df

 * postgresql://localhost/math_db
   postgresql://localhost/student_db
5 rows affected.


,id,name,score
0,1,Alice,85
1,2,Bob,92
2,3,Charlie,67
3,4,David,74
4,5,Eva,90


## NumPy Operations

In [37]:
import numpy as np

scores = df['score'].values

scores + 5
scores * 1.1
scores / 10
scores ** 2


array([7225, 8464, 4489, 5476, 8100])

## Aggregate with NumPy

In [38]:
np.mean(scores)

np.float64(81.6)

In [39]:
np.max(scores)

np.int64(92)

In [40]:
np.min(scores)

np.int64(67)

In [41]:
np.sum(scores)

np.int64(408)

## Advanced Math

In [42]:
np.sqrt(scores)
np.log(scores)
np.exp(scores)

array([8.22301271e+36, 9.01762841e+39, 1.25236317e+29, 1.37338298e+32,
       1.22040329e+39])

## ML Feature Scaling

In [43]:
normalized = (scores - np.mean(scores)) / np.std(scores)
normalized

array([ 0.35401305,  1.08286344, -1.52017368, -0.79132328,  0.87462047])